version: "3.9"

volumes:
  eshop-fd-db:
  eshop-fd-data:

services:

  mongodb:
    image: 'mongo'
    volumes:
      - eshop-fd-db:/data/db
    container_name: db.eshop-fd
    environment:
      MONGO_INITDB_DATABASE: eshop
    restart: always

  backend:
    build: ./backend
    container_name: backend.eshop-fd
    environment:
      DATABASE_URL: mongodb://db.eshop-fd/bosan
    volumes:
      - eshop-fd-data:/data
    depends_on:
      - mongodb
    restart: always
    ports:
      - '3000:3000'

  frontend:
    build: ./frontend
    container_name: frontend.eshop-fd
    ports:
      - '80:80'
    restart: always
    depends_on:
      - backend
