# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  frontend:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      working-directory: ./frontend
    - run: npm run build --if-present
      working-directory: ./frontend
    - run: rm -r /var/www/eshop.fd.cvut.cz/html && cp -r /var/www/eshop.fd.cvut.cz/actions-runner/eshop/eshop-fd/eshop-fd/frontend/dist/ /var/www/eshop.fd.cvut.cz/html/
    - run: npm ci
      working-directory: ./backend
    - run: nest build
      working-directory: ./backend
    - run: cp -r /var/www/eshop.fd.cvut.cz/actions-runner/eshop/eshop-fd/eshop-fd/backend/dist/* /var/www/eshop.fd.cvut.cz/server/
    - run: pm2 restart 1
